name: tailwind_flutter_example
description: Example app demonstrating tailwind_flutter
publish_to: none
version: 0.0.1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  tailwind_flutter:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
